### ISSUE TITLE
引用后出现Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by telfordNiu** [wg5945/vue-marquee-tips#1]
import MarqueeTips from 'vue-marquee-tips'后
出现Uncaught SyntaxError: Unexpected token import
去掉后，项目运行正常，请问什么原因？

**Comment by wg5945** [comment]
import是es6语法，需使用babel将es6转换成es5

**Comment by telfordNiu** [comment]
babel是有的，其他import的都正常。就是引用这个后，不正常，不知道是不是编译时出什么问题了

**Comment by telfordNiu** [comment]
原因已经找到，我的项目是webpack1，要进行升级到2

**Comment by wg5945** [comment]
额，我使用的貌似是最新的vue-cli
