### ISSUE TITLE
可以麻煩修改package.json 的main 改成build 之後的版本嗎

### ISSUE THREAD

**Issue by aloha1003** [wg5945/vue-marquee-tips#5]
你好，我安裝之後，發現會出現 es6 編譯問題
可以先用babel build ，把package.json 的main 改成 complie 之後的版本嗎，謝謊

**Comment by zhanghuanchong** [comment]
@aloha1003 
可以用：
`import MarqueeTips from '../../../node_modules/vue-marquee-tips/src/components/MarqueeTips.vue'`

**Comment by wg5945** [comment]
fixed
