### ISSUE TITLE
deleteKeyFrame方法不完善， insertKeyFrame   0% 值设置为text-indent: 100%  有可能会更好

### ISSUE THREAD

**Issue by wuyinxing** [wg5945/vue-marquee-tips#7]
项目终遇到：
1 、 deleteKeyFrame ： 通过styleSheets找可能不准确， 会遇到不匹配cssRules（rules）的情况
2 、 0%的时候计算宽度不是很准确！

**Comment by wuyinxing** [comment]
> 我也遇到类似的问题【Exception: DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules at CSSStyleSheet】，请问您最后是如何解决的呢

我把这个组件本地化了，然后然后把出差的 js 部分代码修改了下！

**Comment by wg5945** [comment]
fixed
